cronjob:
  runtime: "* 2 * * * *"

nodeSelector: {}

tolerations: []

annotations: {}

clickhouse:
  enable: true
  ttl:
    tables:
      - name: event_log
        operation: delete
        ttl_column: created_at
        retention: 2
      - name: observations
        operation: delete
        ttl_column: created_at
        retention: 2
      - name: traces
        operation: delete
        ttl_column: created_at
        retention: 2
      - name: scores
        operation: delete
        ttl_column: created_at
        retention: 2
      - name: system.trace_log
        operation: truncate
        ttl_column: event_time
      - name: system.text_log
        operation: truncate
        ttl_column: event_time
  host: "langfuse-clickhouse.default.svc.cluster.local"
  port: "9000"
  user: "default"
  password: "123456"
