cronjob:
  runtime: "* * * * *"

nodeSelector: {}

tolerations: []

annotations: {}

clickhouse:
  enable: true
  cluster_enabled: false         
  cluster_name: default 
  ttl:
    tables:
      - name: event_log
        operation: delete
        ttl_column: created_at
        retention: 2
      - name: observations
        operation: delete
        ttl_column: created_at
        retention: 2
      - name: traces
        operation: delete
        ttl_column: created_at
        retention: 2
      - name: scores
        operation: delete
        ttl_column: created_at
        retention: 2
  host: "mars-langfuse-clickhouse"
  port: "9000"
  user: "default"
  password: "123456"
