cronjob:
  runtime: "0 2 * * *"

nodeSelector: {}

tolerations: []

clickhouse:
  enable: true
  retention:
    days: 30
  host: "langfuse-clickhouse"
  port: "9000"
  user: "default"
  password: "changeme"
