# This values.yaml file demonstrates how to use the basic chart with a single, pre-created secret.
# Secrets must be set manually or via External Secrets Operator like https://external-secrets.io/latest or any other secret management tool.
langfuse:
  ingress:
    enable: true
  resources:
    limits:
      cpu: "300m"
      memory: "512Mi"
    requests:
      cpu: "300m"
      memory: "512Mi"
  salt:
    value: "changeme"

  nextauth:
    secret:
      value: "changeme"

postgresql:
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
  auth:
    username: postgres
    password: "123456"

clickhouse:
  resources:
    limits:
      cpu: "300m"
      memory: "1024Mi"
    requests:
      cpu: "100m"
      memory: "1024Mi"
  auth:
    username: default
    password: "123456"

redis:
  resources:
    limits:
      cpu: "50m"
      memory: "64Mi"
    requests:
      cpu: "25m"
      memory: "32Mi"
  auth:
    password: "123456"
