{{- if .Values.clickhouse.enable }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: clickhouse-delete-cronjob
  labels:
{{ include "common.labels" . | indent 4 }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
spec:
  schedule: "{{ .Values.cronjob.runtime }}"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - name: clickhouse-client
            image: yandex/clickhouse-client:21.3.20.1
            env:
            - name: CLICKHOUSE_HOST
              value: "{{ .Values.clickhouse.host }}"
            - name: CLICKHOUSE_PORT
              value: "{{ .Values.clickhouse.port }}"
            - name: CLICKHOUSE_USER
              value: "{{ .Values.clickhouse.user }}"
            - name: CLICKHOUSE_PASSWORD
              value: "{{ .Values.clickhouse.password }}"
            command:
            - /bin/sh
            - -c
            - |
              set -e
              {{- range .Values.clickhouse.ttl.tables }}
              echo "Processing table: {{ .name }}"

              {{- if and (eq .operation "delete") .retention }}
              THRESHOLD=$(date --utc --date='{{ .retention }} days ago' '+%Y-%m-%d %H:%M:%S')
              echo "  Expired time: $THRESHOLD"

              clickhouse-client --host ${CLICKHOUSE_HOST} --port ${CLICKHOUSE_PORT} \
                --user ${CLICKHOUSE_USER} --password ${CLICKHOUSE_PASSWORD} \
                --query "ALTER TABLE {{ .name }} ON CLUSTER default DELETE WHERE {{ .ttl_column }} < toDateTime('$THRESHOLD')"

              {{- else }}
              echo "  Skipping table {{ .name }}: missing retention or unknown operation"
              {{- end }}

              {{- end }}
          restartPolicy: OnFailure
{{- if and (.Values.nodeSelector) }}
          nodeSelector:
{{ toYaml .Values.nodeSelector | indent 12 }}
    {{- end }}
    {{- if and (.Values.tolerations) }}
          tolerations:
{{ toYaml .Values.tolerations | indent 12 }}
    {{- end }}
{{- end }}