apiVersion: batch/v1
kind: Job
metadata:
  name: clickhouse-retention-job-{{ now | unixEpoch }}
  labels:
{{ include "common.labels" . | indent 4 }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: clickhouse-client
        image: yandex/clickhouse-client:21.3.20.1
        command:
        - /bin/sh
        - -c
        - |
          set -e
          {{- range .Values.clickhouse.ttl.tables }}
          echo "Setting TTL for {{ .name }} ...";
          clickhouse-client --host={{ $.Values.clickhouse.host }} --port={{ $.Values.clickhouse.port }} --user {{ $.Values.clickhouse.user }} --password {{ $.Values.clickhouse.password }} --query="ALTER TABLE {{ .name }} MODIFY TTL toDateTime({{ .ttl_column }}) + INTERVAL {{ .interval }};";
          {{- end }}
      restartPolicy: OnFailure
{{- if and (.Values.nodeSelector) }}
          nodeSelector:
{{ toYaml .Values.nodeSelector | indent 12 }}
    {{- end }}
    {{- if and (.Values.tolerations) }}
          tolerations:
{{ toYaml .Values.tolerations | indent 12 }}
    {{- end }}